### ISSUE TITLE
Flathub link: "404 - Page not found  We couldn't find the page you were looking for"

### ISSUE THREAD

**Issue by heidiwenger** [flathub/com.obsproject.Studio.Plugin.BackgroundRemoval#2]
https://flathub.org/apps/com.obsproject.Studio.Plugin.BackgroundRemoval

So, there is still a problem and not getting the plugin into Flathub? But what is the problem? Thanks.

**Comment by umireon** [comment]
I suppose this plugin is not an app so there is no app page for this plugin.

You can still install this plugin by the command `flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval`.

**Comment by heidiwenger** [comment]
> I suppose this plugin is not an app so there is no app page for this plugin.
> 
> You can still install this plugin by the command `flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval`.

But there is still a link to a spot in Flathub on the main page? Why is that then? To reserve it for future or so? The thing that plugins apparently are not listed on Flathub makes it confusing for new Linux users again, does it not? 

Why not just accept plugins there. The need to even open the terminal then again is also another area of fright for Linux new comers (and most don't even know where to copy paste that command to start with, and others try to TYPE that "flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval" getting single character wrong and it goes south).

I suppose this is yet another problem, even though flatpaks (and snaps) were supposed to make installing things easy regardless of a distro or a distro version. It could be solved by accepting plugins and whatnot too on flatpak, thus making em "click to install".

**Comment by umireon** [comment]
We have nothing to do with FlatHub website so that please report this problem to the upstream like https://github.com/flathub/flathub.

**Comment by umireon** [comment]
@royshil There are nothing to do on our side. Can you close this issue?

**Comment by royshil** [comment]
closing. nothing to do here
